IdentityTest2/Models/AspNetUser_Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser_Category
{

    public int usercategoryId { get; set; }

    public int userId { get; set; }

    public int categoryId { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual Category Category { get; set; }

}

}

IdentityTest2/Controllers/AspNetUser_CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentityTest2.Models;
using Microsoft.AspNet.Identity;
using System.Text;

namespace IdentityTest2.Controllers
{
    [Authorize]
    public class AspNetUser_CategoryController : Controller
    {
        private kapymvc1Entities db = new kapymvc1Entities();

        // GET: AspNetUser_Category
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var aspNetUser_Category = db.AspNetUser_Category.Include(a => a.AspNetUser).Include(a => a.Category);
            return View(aspNetUser_Category.ToList());
        }

        // GET: AspNetUser_Category/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser_Category aspNetUser_Category = db.AspNetUser_Category.Find(id);
            if (aspNetUser_Category == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser_Category);
        }

        // GET: AspNetUser_Category/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.userId = User.Identity.GetUserId<int>();
            //ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName");
            return View();
        }

        // POST: AspNetUser_Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "usercategoryId,userId,categoryId")] AspNetUser_Category aspNetUser_Category)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUser_Category.Add(aspNetUser_Category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", aspNetUser_Category.userId);
            ViewBag.userId = User.Identity.GetUserId<int>();
            //ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName", aspNetUser_Category.categoryId);
            return View(aspNetUser_Category);
        }

        // GET: AspNetUser_Category/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser_Category aspNetUser_Category = db.AspNetUser_Category.Find(id);
            if (aspNetUser_Category == null)
            {
                return HttpNotFound();
            }
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", aspNetUser_Category.userId);
            ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName", aspNetUser_Category.categoryId);
            return View(aspNetUser_Category);
        }

        // POST: AspNetUser_Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "usercategoryId,userId,categoryId")] AspNetUser_Category aspNetUser_Category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser_Category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", aspNetUser_Category.userId);
            ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName", aspNetUser_Category.categoryId);
            return View(aspNetUser_Category);
        }

        // GET: AspNetUser_Category/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser_Category aspNetUser_Category = db.AspNetUser_Category.Find(id);
            if (aspNetUser_Category == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser_Category);
        }

        // POST: AspNetUser_Category/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AspNetUser_Category aspNetUser_Category = db.AspNetUser_Category.Find(id);
            db.AspNetUser_Category.Remove(aspNetUser_Category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //[HttpPost]
        //public ActionResult ListSelectedCategories()
        //{
        //    int userId = User.Identity.GetUserId<int>();
        //    if (userId != 0)
        //    {
        //        var selectedCategoriesModel = db.Categories.Where(c => c.AspNetUser_Category.Any(u => u.userId == userId));
        //        IEnumerable<Category> selectCategories = selectedCategoriesModel.ToList();
        //        StringBuilder sb = new StringBuilder();
        //        sb.Append("You have selected categories: " );
        //        foreach (var c in selectCategories)
        //        {
        //            sb.Append(c.categoryName + " ");
        //        }

        //        ViewBag.message = sb.ToString();
        //        return ViewBag;
        //    }
        //    else {

        //        return ViewBag;
        //    }
        //}
        [HttpGet]
        public ActionResult ListCategories()
        {
            int user_id = User.Identity.GetUserId<int>();
            if (user_id != 0)
            {
                StringBuilder sb = new StringBuilder();
                int num = 0;
                IEnumerable<AspNetUser_Category> selectCategories = db.AspNetUser_Category.Where(n => n.userId == user_id);
                foreach (var row in selectCategories)
                {
                    num++;
                }
                if (num==0)
                {
                    sb.Append("You haven't selected any categories! ");
                }
                else {
                    sb.Append("You have selected categories: ");
                    foreach (var row in selectCategories)
                    {
                        sb.Append(row.Category.categoryName + ", ");
                    }
                    sb.Remove(sb.ToString().LastIndexOf(", "), 1);
                    
                }
                ViewBag.Message = sb.ToString();
            }

            return View();

        }
        [HttpGet]
        public ActionResult Insert()
        {

            return View(db.Categories.ToList());

        }

        [HttpPost, ActionName("Insert")]
        public ActionResult Insert(IEnumerable<Category> categories)
        {
            bool isAdded = false;
            int userId = User.Identity.GetUserId<int>();
            if (userId == 0)
            {
                ViewBag.message = "Sorry, please login or register First";
                return View("InsertResult");
            }
            else {

                if (categories == null || categories.Count(x => x.isSelected == true) == 0)
                {
                    ViewBag.Message = "You haven't selected any category";
                    return View("InsertResult");
                }
                else {
                    StringBuilder sb2 = new StringBuilder();
                    sb2.Append("You have selected categories: ");
                    IEnumerable<AspNetUser_Category> selectCategories = db.AspNetUser_Category.Where(n => n.userId == userId);
                    foreach (var row in selectCategories)
                    {
                        sb2.Append(row.Category.categoryName + "   ");
                    }
                    ViewBag.selectedCategories = sb2.ToString();

                    StringBuilder sb = new StringBuilder();
                    sb.Append("You have successfully selected:  ");
                    foreach (Category c in categories)
                    {
                        IEnumerable<AspNetUser_Category> aspNetUser_Categories = db.AspNetUser_Category.Where(n => n.userId == userId);
                        foreach (var row in aspNetUser_Categories)
                        {
                            if (c.categoryId == row.categoryId)
                            {
                                isAdded = true;
                            }
                        }
                        if (c.isSelected == true && !isAdded)
                        {
                            sb.Append(c.categoryName + " ");
                            if (ModelState.IsValid)
                            {
                                var save = new AspNetUser_Category
                                {
                                    userId = User.Identity.GetUserId<int>(),
                                    categoryId = c.categoryId
                                };
                                db.AspNetUser_Category.Add(save);

IdentityTest2/Views/AspNetUser_Category/Create.cshtml
@model IdentityTest2.Models.AspNetUser_Category


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AspNetUser_Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @ViewBag.userId;
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryId, "categoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })*@
                @Html.Action("_CategoryList", "News1")

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdentityTest2/Views/AspNetUser_Category/Delete.cshtml
@model IdentityTest2.Models.AspNetUser_Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetUser_Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.categoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.categoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IdentityTest2/Views/AspNetUser_Category/Details.cshtml
@model IdentityTest2.Models.AspNetUser_Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AspNetUser_Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.categoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.categoryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.usercategoryId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IdentityTest2/Views/AspNetUser_Category/Edit.cshtml
@model IdentityTest2.Models.AspNetUser_Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AspNetUser_Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.usercategoryId)

        <div class="form-group">
            @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryId, "categoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdentityTest2/Views/AspNetUser_Category/Index.cshtml
@model IEnumerable<IdentityTest2.Models.AspNetUser_Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.categoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.categoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.usercategoryId }) |
            @Html.ActionLink("Details", "Details", new { id=item.usercategoryId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.usercategoryId })
        </td>
    </tr>
}

</table>

IdentityTest2/Views/AspNetUser_Category/Insert.cshtml
@model IEnumerable<IdentityTest2.Models.Category>
@{
    ViewBag.Title = "Select Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br>

    @*@Html.Partial("ListCategories")*@
    @*@ViewBag.Message*@

<p>
    <div style="font-family:Arial">
        @using (Html.BeginForm("Insert", "AspNetUser_Category", FormMethod.Post))
        {
            <br />
            <h4>Select Categories</h4>
            <br />
            @Html.EditorForModel()
            <br />
            <input type="submit" value="Submit" class="btn btn-default">
        }
    </div>
<p>

IdentityTest2/Views/AspNetUser_Category/InsertResult.cshtml
@{
    ViewBag.Title = "InsertResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (ViewBag.Message != null)
    {
        if (ViewBag.Message == "You haven't selected any category")
        {
           <h2> @ViewBag.Message;</h2>
           <div>
               <input type="button" value="OK" class="btn btn-default" onclick="@("window.location.href='"+Url.Action("Insert","AspNetUser_Category")+"'")">
               @*<input type="button" value="OK" class="btn btn-default" onclick="@Html.ActionLink("Insert", "AspNetUser_Category")">*@
           </div>

        }
        else if (ViewBag.Message == "Sorry, please login or register First")
        {
            <h2> @ViewBag.Message;</h2>
            <div>
                <input type="button" value="OK" class="btn btn-default" onclick="@("window.location.href='"+Url.Action("Login","Account")+"'")">
                @*<input type="button" value="OK" class="btn btn-default" onclick="@Html.ActionLink("Login", "Account")">*@
            </div>
        }
        else {
            <h2> @ViewBag.Message;</h2>
            <div>
                <input type="button" value="OK" class="btn btn-default" onclick="@("window.location.href='"+Url.Action("RecommendToYou","News1")+"'")">
                @*<input type="button" value="OK" class="btn btn-default" onclick="@Html.ActionLink("Recommend","News1")">*@
            </div>

        }


    }
}

IdentityTest2/Views/AspNetUser_Category/ListCategories.cshtml
@{
    ViewBag.Title = "Current Categories";
}
<br>
<br>
<br>
<h2>Your current selected categories:</h2>
<br>

<h3>@ViewBag.Message</h3>