IdentityTest2/Models/Comment1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IdentityTest2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment1
{

    public int commentId { get; set; }

    public int userId { get; set; }

    public int newsId { get; set; }

    public byte[] postTime { get; set; }

    public string commentContent { get; set; }

    public bool isDisplayed { get; set; }

    public Nullable<int> numOfComentLikes { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual News1 News1 { get; set; }

}

}

IdentityTest2/Controllers/Comment1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentityTest2.Models;
using Microsoft.AspNet.Identity;
using System.Text;

namespace IdentityTest2.Controllers
{
    //[Authorize]
    public class Comment1Controller : Controller
    {
        private kapymvc1Entities db = new kapymvc1Entities();

        // GET: Comment1
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var comment1 = db.Comment1.Include(c => c.AspNetUser).Include(c => c.News1);
            return View(comment1.ToList());
        }

        // GET: Comment1/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment1 comment1 = db.Comment1.Find(id);
            if (comment1 == null)
            {
                return HttpNotFound();
            }
            return View(comment1);
        }

        // GET: Comment1/Create
        
        public ActionResult Create()
        {
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.newsId = new SelectList(db.News1, "newsId", "uniqueTitle");
            return View();
        }

        // POST: Comment1/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "commentId,userId,newsId,postTime,commentContent,isDisplayed,numOfComentLikes")] Comment1 comment1)
        {
            if (ModelState.IsValid)
            {
                db.Comment1.Add(comment1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", comment1.userId);
            ViewBag.newsId = new SelectList(db.News1, "newsId", "uniqueTitle", comment1.newsId);
            return View(comment1);
        }

        // GET: Comment1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment1 comment1 = db.Comment1.Find(id);
            if (comment1 == null)
            {
                return HttpNotFound();
            }
            ViewBag.userId = User.Identity.GetUserId<int>();
            //ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", comment1.userId);
            //ViewBag.newsId = new SelectList(db.News1, "newsId", "uniqueTitle", comment1.newsId);
            ViewBag.newsId = comment1.newsId;
            return View(comment1);
        }

        // POST: Comment1/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "commentId,userId,newsId,postTime,commentContent,isDisplayed,numOfComentLikes")] Comment1 comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                comment.numOfComentLikes = 0;
                db.SaveChanges();
                return RedirectToAction("Details", "News1", new { id = comment.newsId });
            }

            ViewBag.userId = comment.userId;
            ViewBag.newsId = comment.newsId;
            //ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", comment1.userId);
            //ViewBag.newsId = new SelectList(db.News1, "newsId", "uniqueTitle", comment1.newsId);
            return View(comment);
        }

        // GET: Comment1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment1 comment1 = db.Comment1.Find(id);
            if (comment1 == null)
            {
                return HttpNotFound();
            }
            ViewBag.newsID = comment1.newsId;
            return View(comment1);
        }

        // POST: Comment1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment1 comment = db.Comment1.Find(id);
            db.Comment1.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Details", "News1", new { id = comment.newsId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //This function retrieve all comments for a given news
        //the id parameter is the news ID
        // GET: Comments/CommentForNews/5
        public ActionResult CommentForNews(int? id, string sortOrder)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var news = db.News1.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            var commentNews = db.Comment1.Include(c => c.AspNetUser).Include(c => c.News1).Where(x => x.newsId == id);
            var newsTitle = db.News1.Single(x => x.newsId == id).newsTitle;
            ViewBag.newsTitle = newsTitle;
            ViewBag.newsID = id;
            ViewBag.user_id = User.Identity.GetUserId<int>();
            //The comments will be sorted by the number of likes
            ViewBag.DateSortParm = sortOrder == "ID" ? "Time" : "ID";
            switch (sortOrder)
            {

                case "ID":
                    commentNews = commentNews.OrderBy(c => c.commentId);
                    break;
                case "Time":
                    commentNews = commentNews.OrderByDescending(c => c.postTime);
                    break;
                default:
                    commentNews = commentNews.OrderByDescending(c => c.numOfComentLikes);
                    break;
            }

            return View(commentNews.ToList());
        }

        // GET: Comments/CreateCommentForNews/5
        public ActionResult CreateCommentForNews(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var news = db.News1.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }

            var user_id = User.Identity.GetUserId<int>();
            var article = db.News1.Single(x => x.newsId == id);
            if (user_id == 0)
            {
                ViewBag.message = "Please login or register first.";
                return View("LoginFirstView", article);
            }
            else {
                ViewBag.message = "ADD A COMMENT";
                ViewBag.userId = User.Identity.GetUserId<int>();
                ViewBag.newsId = id;
                return View();
                
            }

        }
        //The id here is for the newsID of the news this comment is being written on
        // POST: Comments/CreateCommentForNews/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCommentForNews(int id, [Bind(Include = "commentId,userId,newsId,postTime,commentContent,isDisplayed,numOfComentLikes")] Comment1 comment)
        {
            var user_id = User.Identity.GetUserId<int>();
            var article = db.News1.Single(x => x.newsId == id);

            if (user_id == 0)
            {
                
                String returnURL = "Comments/CreateCommentForNews/" + id;
                return RedirectToAction("Login", "Account", returnURL);
            }

            if (ModelState.IsValid)
            {
                comment.Datetime = DateTime.Now;
                comment.numOfComentLikes = 0;
                ViewBag.message = "ADD A COMMENT";
                comment.newsId = id;
                comment.userId = User.Identity.GetUserId<int>();
                db.Comment1.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Details", "News1", new { id = comment.newsId });
            }

            ViewBag.userId = User.Identity.GetUserId<int>();
            ViewBag.newsId = comment.newsId;
  
            return View(comment);
        }

        // GET: Comments/Like/5

        public ActionResult Like(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment1 comment = db.Comment1.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.commentID = id;
            return PartialView(comment);
        }


        //LikeComment increases the numberOfLikes for a given comment
        // POST: Comments/LikeAComment/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost, ActionName("Like")]
        [HttpPost]
        [ValidateAntiForgeryToken]

IdentityTest2/Views/Comment1/CommentForNews.cshtml
@{
    Layout = "";
}

@model IEnumerable<IdentityTest2.Models.Comment1>

<body>
    <h4> All Comments </h4>



    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AspNetUser.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.commentContent)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.isDisplayed)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.numOfComentLikes)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Datetime)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.News1.uniqueTitle)
                </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (item.isDisplayed)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AspNetUser.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.commentContent)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.numOfComentLikes)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Datetime)
                    </td>

                    @*<td>
                            @Html.DisplayFor(modelItem => item.isDisplayed)
                        </td>*@


                    @*<td>
                            @Html.DisplayFor(modelItem => item.News1.uniqueTitle)
                        </td>*@
                    <td>
                       @if (ViewBag.user_id != 0)
                       {
                            @Html.Action("Like", "Comment1", new { id = item.commentId })    
                        }

                    </td>
                    
                        @if (item.userId == ViewBag.user_id && ViewBag.user_id != 0)
                        {
                            @*<td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.commentId }) 
                            </td>*@
                            <td>
                                @Html.ActionLink("Delete", "Delete", new { id = item.commentId })
                            </td>
                        }
                    
                </tr>
            }
        }

    </table>

    <p>
        @Html.ActionLink("ADD A COMMENT", "CreateCommentForNews", new { id = ViewBag.newsID })
    </p>

</body>

IdentityTest2/Views/Comment1/Create.cshtml
@model IdentityTest2.Models.Comment1

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Comment1</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.newsId, "newsId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("newsId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.newsId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.commentContent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.commentContent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.commentContent, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.isDisplayed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.isDisplayed)
                        @Html.ValidationMessageFor(model => model.isDisplayed, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.numOfComentLikes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.numOfComentLikes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.numOfComentLikes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

IdentityTest2/Views/Comment1/CreateCommentForNews.cshtml
@model IdentityTest2.Models.Comment1


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@ViewBag.message</h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.newsId, "newsId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("newsId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.newsId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.commentContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.commentContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.commentContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDisplayed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDisplayed)
                    @Html.ValidationMessageFor(model => model.isDisplayed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.numOfComentLikes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.numOfComentLikes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.numOfComentLikes, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to the News", "Details", "News1", new { id = ViewBag.newsID}, null);
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdentityTest2/Views/Comment1/Delete.cshtml
@model IdentityTest2.Models.Comment1

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment1</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commentContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commentContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDisplayed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numOfComentLikes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numOfComentLikes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.News1.uniqueTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.News1.uniqueTitle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", "News1", new { id = ViewBag.newsID }, null)
        </div>
    }
</div>

IdentityTest2/Views/Comment1/Details.cshtml
@model IdentityTest2.Models.Comment1

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Comment1</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.postTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.postTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commentContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commentContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDisplayed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numOfComentLikes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numOfComentLikes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.News1.uniqueTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.News1.uniqueTitle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.commentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IdentityTest2/Views/Comment1/Edit.cshtml
@model IdentityTest2.Models.Comment1

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Are you sure you want to edit this comment?</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.commentId)

        @*<div class="form-group">
            @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.newsId, "newsId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("newsId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.newsId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.postTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.postTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.postTime, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.commentContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.commentContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.commentContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDisplayed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDisplayed)
                    @Html.ValidationMessageFor(model => model.isDisplayed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.numOfComentLikes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numOfComentLikes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numOfComentLikes, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
     @Html.ActionLink("Back to List", "Details", "News1", new { id = ViewBag.newsID }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdentityTest2/Views/Comment1/Index.cshtml
@model IEnumerable<IdentityTest2.Models.Comment1>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.postTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.commentContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isDisplayed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.numOfComentLikes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.News1.uniqueTitle)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.postTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.commentContent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isDisplayed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.numOfComentLikes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.News1.uniqueTitle)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.commentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.commentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.commentId })
        </td>
    </tr>
}

</table>

IdentityTest2/Views/Comment1/Like.cshtml
@model IdentityTest2.Models.Comment1

@{
    Layout = "";
}

@using (Html.BeginForm("LikeAComment", "Comment1", new { id = @ViewBag.commentID }, FormMethod.Post, null))
{
    @Html.AntiForgeryToken()


    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Like" class="btn btn-default" />
    </div>


}

IdentityTest2/Views/Comment1/LoginFirstView.cshtml
@model IdentityTest2.Models.News1


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>To comment on </h4>
        
        <p>
            <h2> <a href="@Html.DisplayFor(model => model.origUrl) ">@Html.DisplayFor(model => model.newsTitle)</a>  </h2>
        </p>

        

        @*<h4>@ViewBag.message</h4>*@

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login or Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}